#!/bin/bash

set -e # exit if command fails

DCONF_PROFILE="/etc/dconf/profile/user"
DCONF_GDM_PROFILE="/etc/dconf/profile/gdm"
mkdir -p /etc/dconf/profile

# avoid double-writing
if [ ! -f "$DCONF_PROFILE" ] || ! grep -q "system-db:local" "$DCONF_PROFILE"; then
    echo "user-db:user" > "$DCONF_PROFILE"
    echo "system-db:local" >> "$DCONF_PROFILE"
fi

if [ ! -f "$DCONF_GDM_PROFILE" ] || ! grep -q "system-db:gdm" "$DCONF_GDM_PROFILE"; then
	echo "user-db:user" > "$DCONF_GDM_PROFILE"
	echo "system-db:gdm" >> "$DCONF_GDM_PROFILE"
	echo "file-db:/usr/share/gdm/greeter-dconf-defaults" >> "$DCONF_GDM_PROFILE" # https://support.scc.suse.com/s/kb/How-to-set-a-global-dconf-value-for-gnome-gdm-1583239433993?language=en_US
fi

if command -v dconf >/dev/null 2>&1; then
    echo "Updating dconf database..."
    dconf update
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
	echo "Updating icon cache..."
	gtk-update-icon-cache /usr/share/icons/*
fi

BASHRC=/etc/skel/.bashrc

APT_FUNCTION_HEADER="# --- UTILE OS NALA CONFIG START --- #"
APT_FUNCTION_FOOTER="# --- UTILE OS NALA CONFIG END --- #"

if [ -f $BASHRC ]; then
	if grep -q "$APT_FUNCTION_HEADER" "$BASHRC"; then
		echo "Updating nala apt wrapper in $BASHRC"
	else
		echo "Configuring apt command to use nala..."
	fi

	sed -i "/$APT_FUNCTION_HEADER/,/$APT_FUNCTION_FOOTER/d" "$BASHRC" || true
	perl -pi -e 'chomp if eof' $BASHRC || true
	(cat << 'EOF'

# --- UTILE OS NALA CONFIG START --- #
apt() {
	HEADER="\e[31mUtile OS uses nala for this 'apt' command. To only use apt: modify your .bashrc, use 'sudo', or use 'apt-get'.\e[0m"
	if [[ "$1" == "history" || "$1" == "list" || "$1" == "search" || "$1" == "show" ]]; then
		echo -e "$HEADER"
		nala "$@"
	elif [[ "$1" == "autoclean" || "$1" == "reinstall" || "$1" == "satisfy" || "$1" == "source" || "$1" == "edit-sources" || "$2" == "--only-upgrade" || "$2" == "--reinstall" || "$2" == "--allow-downgrades" ]]; then
		sudo "apt" "$@"
	else
		echo -e "$HEADER"
		sudo nala "$@"
	fi
}
# --- UTILE OS NALA CONFIG END --- #
EOF
) >> $BASHRC
fi

# Default neofetch
if [ -f $BASHRC ]; then
	# Remove previous aliases as well as trailing newlines
	sed -i '/alias fastfetch/d;/alias neofetch/d' $BASHRC || true
	perl -pi -e 'chomp if eof' $BASHRC || true

	# Add new aliases
	(cat << 'EOF'

alias fastfetch="fastfetch --logo /usr/share/pixmaps/utile-ascii.txt --config utile.jsonc"
alias neofetch="fastfetch"
EOF
) >> $BASHRC
fi