#!/bin/bash

set -e # exit if command fails

DCONF_PROFILE="/etc/dconf/profile/user"
DCONF_GDM_PROFILE="/etc/dconf/profile/gdm"
mkdir -p /etc/dconf/profile

# avoid double-writing
if [ ! -f "$DCONF_PROFILE" ] || ! grep -q "system-db:local" "$DCONF_PROFILE"; then
    echo "user-db:user" > "$DCONF_PROFILE"
    echo "system-db:local" >> "$DCONF_PROFILE"
fi

if [ ! -f "$DCONF_GDM_PROFILE" ] || ! grep -q "system-db:gdm" "$DCONF_GDM_PROFILE"; then
	echo "user-db:user" > "$DCONF_GDM_PROFILE"
	echo "system-db:gdm" >> "$DCONF_GDM_PROFILE"
	echo "file-db:/usr/share/gdm/greeter-dconf-defaults" >> "$DCONF_GDM_PROFILE" # https://support.scc.suse.com/s/kb/How-to-set-a-global-dconf-value-for-gnome-gdm-1583239433993?language=en_US
fi

if command -v dconf >/dev/null 2>&1; then
    echo "Updating dconf database..."
    dconf update
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
	echo "Updating icon cache..."
	gtk-update-icon-cache /usr/share/icons/*
fi

# TODO: Remove this since the configurations are now in /etc/profile.d
BASHRC=/etc/skel/.bashrc

APT_FUNCTION_HEADER="# --- UTILE OS NALA CONFIG START --- #"
APT_FUNCTION_FOOTER="# --- UTILE OS NALA CONFIG END --- #"

if [ -f $BASHRC ]; then
	if grep -q "$APT_FUNCTION_HEADER" "$BASHRC"; then
		echo "Updating nala apt wrapper in $BASHRC"
	else
		echo "Configuring apt command to use nala..."
	fi

	sed -i "/$APT_FUNCTION_HEADER/,/$APT_FUNCTION_FOOTER/d" "$BASHRC" || true
	perl -pi -e 'chomp if eof' $BASHRC || true
fi

# Default neofetch
if [ -f $BASHRC ]; then
	# Remove previous aliases as well as trailing newlines
	sed -i '/alias fastfetch/d;/alias neofetch/d' $BASHRC || true
	perl -pi -e 'chomp if eof' $BASHRC || true
fi

#DEBHELPER#