#!/bin/bash
set -e

BASHRC=/etc/skel/.bashrc

if [ -f $BASHRC ] && ! grep -q "nala" $BASHRC; then
	echo "Configuring apt command to use nala..."
	(cat << 'EOF'

apt() {
	echo -e "\e[31mUtile OS uses nala for 'apt' commands. If you want to use apt: Modify your .bashrc, use sudo, or use apt-get.\e[0m"
	if [[ "$1" == "history" || "$1" == "list" || "$1" == "search" || "$1" == "show" ]]; then
		nala "$@"
	elif [[ "$1" == "autoclean" || "$1" == "reinstall" || "$1" == "satisfy" || "$1" == "source" || "$1" == "edit-sources" ]]; then
		sudo apt "$@"
	else
		sudo nala "$@"
	fi
}
EOF
) >> $BASHRC
fi

# Default neofetch
if [ -f $BASHRC ]; then
	# Remove previous aliases as well as trailing newlines
	sed -i '/alias fastfetch/d;/alias neofetch/d' $BASHRC || true
	perl -pi -e 'chomp if eof' $BASHRC || true

	# Add new aliases
	(cat << 'EOF'

alias fastfetch="fastfetch --logo /usr/share/pixmaps/utile-ascii.txt --config utile.jsonc"
alias neofetch="fastfetch"
EOF
) >> $BASHRC
fi