#!/bin/bash

set -e # exit if command fails

DCONF_PROFILE="/etc/dconf/profile/user"
DCONF_GDM_PROFILE="/etc/dconf/profile/gdm"
mkdir -p /etc/dconf/profile

# avoid double-writing
if [ ! -f "$DCONF_PROFILE" ] || ! grep -q "system-db:local" "$DCONF_PROFILE"; then
    echo "user-db:user" > "$DCONF_PROFILE"
    echo "system-db:local" >> "$DCONF_PROFILE"
fi

if [ ! -f "$DCONF_GDM_PROFILE" ] || ! grep -q "system-db:local" "$DCONF_GDM_PROFILE"; then
	echo "user-db:user" > "$DCONF_GDM_PROFILE"
	echo "system-db:local" >> "$DCONF_GDM_PROFILE"
fi

if command -v dconf >/dev/null 2>&1; then
    echo "Updating dconf database..."
    dconf update
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
	echo "Updating icon cache..."
	gtk-update-icon-cache /usr/share/icons/*
fi

exit 0